version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5256:5256" 
    environment:
      - ASPNETCORE_URLS=http://+:5256
    networks:
      - mars-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    depends_on:
      - backend
    networks:
      - mars-network

networks:
  mars-network:
    driver: bridge